module.exports = {
  apps: [
    {
      name: "ecointel-api-gateway",
      script: "src/api/server.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "512M",
      env_production: {
        NODE_ENV: "production",
        PORT: 4052,
        LOG_LEVEL: "info",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        GITHUB_TOKEN: process.env.GITHUB_TOKEN || "",
        ECOINTEL_API_KEY: process.env.ECOINTEL_API_KEY || "sk_ecointel_default",
        EMBED_SERVICE_URL: "http://localhost:4054",
      },
      env_development: {
        NODE_ENV: "development",
        PORT: 4052,
        LOG_LEVEL: "debug",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        GITHUB_TOKEN: process.env.GITHUB_TOKEN || "",
        ECOINTEL_API_KEY: "sk_ecointel_dev",
        EMBED_SERVICE_URL: "http://localhost:4054",
      },
      merge_logs: true,
      error_file: "logs/ecointel-api-gateway-error.log",
      out_file: "logs/ecointel-api-gateway-out.log",
    },
    {
      name: "ecointel-ingest-worker",
      script: "src/workers/ingest-worker.js",
      instances: 4,
      exec_mode: "cluster",
      env_production: {
        NODE_ENV: "production",
        LOG_LEVEL: "info",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        GITHUB_TOKEN: process.env.GITHUB_TOKEN || "",
      },
      env_development: {
        NODE_ENV: "development",
        LOG_LEVEL: "debug",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        GITHUB_TOKEN: process.env.GITHUB_TOKEN || "",
      },
      merge_logs: true,
      error_file: "logs/ecointel-ingest-worker-error.log",
      out_file: "logs/ecointel-ingest-worker-out.log",
    },
    {
      name: "ecointel-embed-bridge",
      script: "src/workers/embed-bridge.js",
      instances: 2,
      exec_mode: "cluster",
      env_production: {
        NODE_ENV: "production",
        LOG_LEVEL: "info",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        EMBED_SERVICE_URL: "http://localhost:4054",
      },
      env_development: {
        NODE_ENV: "development",
        LOG_LEVEL: "debug",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        EMBED_SERVICE_URL: "http://localhost:4054",
      },
      merge_logs: true,
      error_file: "logs/ecointel-embed-bridge-error.log",
      out_file: "logs/ecointel-embed-bridge-out.log",
    },
    {
      name: "ecointel-score-worker",
      script: "src/workers/score-worker.js",
      instances: 4,
      exec_mode: "cluster",
      env_production: {
        NODE_ENV: "production",
        LOG_LEVEL: "info",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        WEIGHT_VERSION: "v1.0",
      },
      env_development: {
        NODE_ENV: "development",
        LOG_LEVEL: "debug",
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/ecointel",
        REDIS_URL: "redis://localhost:6379",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        WEIGHT_VERSION: "v1.0",
      },
      merge_logs: true,
      error_file: "logs/ecointel-score-worker-error.log",
      out_file: "logs/ecointel-score-worker-out.log",
    },
    {
      name: "ecointel-mcp-server",
      script: "src/mcp/server.js",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        NODE_ENV: "production",
        LOG_LEVEL: "info",
        ECOINTEL_API_URL: "http://localhost:4052",
        ECOINTEL_API_KEY: process.env.ECOINTEL_API_KEY || "sk_ecointel_default",
      },
      env_development: {
        NODE_ENV: "development",
        LOG_LEVEL: "debug",
        ECOINTEL_API_URL: "http://localhost:4052",
        ECOINTEL_API_KEY: "sk_ecointel_dev",
      },
      merge_logs: true,
      error_file: "logs/ecointel-mcp-server-error.log",
      out_file: "logs/ecointel-mcp-server-out.log",
    },
    {
      name: "ecointel-embed-service",
      script: "src/workers/embed-worker.py",
      interpreter: "python3",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        EMBED_MODEL: "BAAI/bge-m3",
        QDRANT_URL: "http://localhost:6333",
        PORT: 4054,
      },
      env_development: {
        EMBED_MODEL: "sentence-transformers/all-MiniLM-L6-v2",
        QDRANT_URL: "http://localhost:6333",
        PORT: 4054,
      },
      merge_logs: true,
      error_file: "logs/ecointel-embed-service-error.log",
      out_file: "logs/ecointel-embed-service-out.log",
    },
  ],

  deploy: {
    production: {
      user: "node",
      host: "your-server.com",
      ref: "origin/main",
      repo: "git@github.com:your-org/ecointel-api.git",
      path: "/var/www/ecointel-api",
      "post-deploy":
        "npm install && npm run db:migrate && pm2 startOrRestart ecosystem.config.js --env production",
    },
  },
};
